---
name: reviewdog
on:  # yamllint disable-line rule:truthy
  push:

jobs:

  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: yamllint
        uses: reviewdog/action-yamllint@v1.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check

  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-black@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
