---
name: Gauge specs
on:  # yamllint disable-line rule:truthy
  # Run the tests on every push, and also at 3am every night
  push:
  schedule:
    - cron: '0 3 * * *'  # * is a special character in YAML so you have to quote this string

jobs:
  tests:
    name: ${{ matrix.gauge-env }} server
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        gauge-env: [default, mock, validation-proxy]
    steps:

      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-plugins: python, html-report

      - name: Install OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Generate OpenAPI Python SDK client
        run: openapi-generator-cli generate -i openapi.yaml -g python -o ./python-client-generated

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install OpenAPI Python SDK client
        working-directory: ./python-client-generated
        run: python setup.py install

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Prism
        run: npm install -g @stoplight/prism-cli

      - name: Start Prism in mock mode
        if: matrix.gauge-env == 'mock'
        run: prism mock openapi.yaml &

      - name: Start Prism in validation proxy mode
        if: matrix.gauge-env == 'validation-proxy'
        run: prism proxy openapi.yaml https://petstore.swagger.io/v2 --errors &

      - name: Run Gauge specs against ${{ matrix.gauge-env }} OpenAPI server
        run: gauge run --env ${{ matrix.gauge-env }} specs

      - name: Upload Gauge test report
        uses: actions/upload-artifact@v2
        with:
          name: gauge-html-report
          path: reports/html-report/
