---
name: Gauge specs
on:  # yamllint disable-line rule:truthy
  # Run the tests on every push, and also at 3am every night
  push:
  schedule:
    - cron: "0 3 * * *"  # * is a special character in YAML so you have to quote this string

jobs:
  tests:
    name: Mock server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-plugins: python, html-report

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Prism
        run: npm install -g @stoplight/prism-cli

      - name: Start Prism in mock mode
        run: prism mock openapi.yaml &

      - name: Run Gauge specs against mock OpenAPI server
        # Env var is temporary workaround for https://github.com/getgauge/gauge-python/issues/256
        env:
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
        run: gauge run specs

      - name: Upload Gauge test report
        uses: actions/upload-artifact@v2
        with:
          name: gauge-html-report
          path: reports/html-report/
