---
on:  # yamllint disable-line rule:truthy
  push:

name: Tests
jobs:
  tests:
    name: Gauge Specs
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-plugins: python, html-report

      - name: Install OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Generate OpenAPI Python SDK client
        run: openapi-generator-cli generate -i openapi.yaml -g python -o ./python-client-generated

      - name: Install Prism
        run: npm install -g @stoplight/prism-cli

      - name: Start Prism
        run: prism mock openapi.yaml &

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install OpenAPI Python SDK client
        working-directory: ./python-client-generated
        run: python setup.py install

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Gauge specs against real OpenAPI server
        run: gauge run specs

      - name: Run Gauge specs against mock OpenAPI server
        run: gauge run --env mock specs
